### ISSUE TITLE
Client Crashes When Approaching Another Player on Server

### ISSUE THREAD

**Issue by Rovmonger** [skyjay1/GreekFantasy-1.16#1]
Player client crashes when close to another player. 
Crash Report attached.
[crash-2020-11-08_16.21.16-client.txt](https://github.com/skyjay1/GreekFantasy-1.16/files/5506686/crash-2020-11-08_16.21.16-client.txt)

**Comment by skyjay1** [comment]
Thank you, I'll upload a fix this week.

**Comment by skyjay1** [comment]
Fixed in build 16.3.1
